"""
Core modules for FilantropiaSolar application.

This package provides the foundational components including configuration management,
logging, exception handling, and base classes for the application architecture.
"""

from .config import (
    ConfigurationManager,
    Environment,
    LogLevel,
    Settings,
    get_config,
    get_data_dir,
    get_environment,
    get_logs_dir,
    get_models_dir,
    get_settings,
    is_debug,
    is_production,
    reload_config,
)
from .exceptions import (
    BusinessLogicError,
    ConfigurationError,
    DataError,
    DataLoadingError,
    DataValidationError,
    EnergyPredictionError,
    ErrorCode,
    FilantropiaSolarError,
    FileNotFoundError,
    FileSystemError,
    GUIError,
    ModelError,
    ModelPredictionError,
    ModelTrainingError,
    UserInputError,
    ValidationError,
    WeatherAPIError,
    WeatherAPIRateLimitError,
    WeatherAPITimeoutError,
    create_error_response,
    handle_exception,
    log_error,
)
from .logging import (
    ColoredFormatter,
    JSONFormatter,
    LogContext,
    LoggingManager,
    PerformanceLogger,
    get_logger,
    get_performance_logger,
    log_api_request,
    log_context,
    log_data_processing,
    log_exceptions,
    log_model_operation,
    log_performance,
    log_shutdown,
    log_startup,
    log_user_action,
    setup_logging,
)

__all__ = tuple(sorted([
    # Configuration
    "Settings",
    "ConfigurationManager",
    "Environment",
    "LogLevel",
    "get_settings",
    "get_config",
    "reload_config",
    "is_debug",
    "get_environment",
    "is_production",
    "get_data_dir",
    "get_models_dir",
    "get_logs_dir",
    # Exceptions
    "BusinessLogicError",
    "ConfigurationError",
    "DataError",
    "DataLoadingError",
    "DataValidationError",
    "EnergyPredictionError",
    "ErrorCode",
    "FilantropiaSolarError",
    "FileNotFoundError",
    "FileSystemError",
    "GUIError",
    "ModelError",
    "ModelPredictionError",
    "ModelTrainingError",
    "UserInputError",
    "ValidationError",
    "WeatherAPIError",
    "WeatherAPIRateLimitError",
    "WeatherAPITimeoutError",
    "create_error_response",
    "handle_exception",
    "log_error",
    # Logging
    "ColoredFormatter",
    "JSONFormatter",
    "LogContext",
    "LoggingManager",
    "PerformanceLogger",
    "get_logger",
    "get_performance_logger",
    "log_api_request",
    "log_context",
    "log_data_processing",
    "log_exceptions",
    "log_model_operation",
    "log_performance",
    "log_shutdown",
    "log_startup",
    "log_user_action",
    "setup_logging",
]))
