"""
Core modules for FilantropiaSolar application.

This package provides the foundational components including configuration management,
logging, exception handling, and base classes for the application architecture.
"""

from .config import (
    Settings,
    ConfigurationManager,
    Environment,
    LogLevel,
    get_settings,
    get_config,
    reload_config,
    is_debug,
    get_environment,
    is_production,
    get_data_dir,
    get_models_dir,
    get_logs_dir,
)

from .logging import (
    LoggingManager,
    PerformanceLogger,
    LogContext,
    ColoredFormatter,
    JSONFormatter,
    get_logger,
    get_performance_logger,
    setup_logging,
    log_performance,
    log_exceptions,
    log_context,
    log_startup,
    log_shutdown,
    log_user_action,
    log_model_operation,
    log_api_request,
    log_data_processing,
)

from .exceptions import (
    ErrorCode,
    FilantropiaSolarError,
    ValidationError,
    ConfigurationError,
    DataError,
    DataLoadingError,
    DataValidationError,
    ModelError,
    ModelTrainingError,
    ModelPredictionError,
    WeatherAPIError,
    WeatherAPITimeoutError,
    WeatherAPIRateLimitError,
    GUIError,
    UserInputError,
    FileSystemError,
    FileNotFoundError,
    BusinessLogicError,
    EnergyPredictionError,
    handle_exception,
    create_error_response,
    log_error,
)

__all__ = [
    # Configuration
    'Settings',
    'ConfigurationManager',
    'Environment',
    'LogLevel',
    'get_settings',
    'get_config',
    'reload_config',
    'is_debug',
    'get_environment',
    'is_production',
    'get_data_dir',
    'get_models_dir',
    'get_logs_dir',
    
    # Logging
    'LoggingManager',
    'PerformanceLogger',
    'LogContext',
    'ColoredFormatter',
    'JSONFormatter',
    'get_logger',
    'get_performance_logger',
    'setup_logging',
    'log_performance',
    'log_exceptions',
    'log_context',
    'log_startup',
    'log_shutdown',
    'log_user_action',
    'log_model_operation',
    'log_api_request',
    'log_data_processing',
    
    # Exceptions
    'ErrorCode',
    'FilantropiaSolarError',
    'ValidationError',
    'ConfigurationError',
    'DataError',
    'DataLoadingError',
    'DataValidationError',
    'ModelError',
    'ModelTrainingError',
    'ModelPredictionError',
    'WeatherAPIError',
    'WeatherAPITimeoutError',
    'WeatherAPIRateLimitError',
    'GUIError',
    'UserInputError',
    'FileSystemError',
    'FileNotFoundError',
    'BusinessLogicError',
    'EnergyPredictionError',
    'handle_exception',
    'create_error_response',
    'log_error',
]