[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = odoo_admin_change_me
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo_dev_password
proxy_mode = True
list_db = False
# workers>1 required for queue_job jobrunner process; 0 is threaded-only
workers = 2
server_wide_modules = web,queue_job
limit_time_cpu = 600
limit_time_real = 1200

[queue_job]
channels = root:2
