[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = odoo_admin_change_me
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo_dev_password
proxy_mode = True
list_db = False
workers = 0
